export const CONFIG_RES = {
  //内部配置
  INNERCONFIG: 'iwms.facility.innerConfig',
  BINVIEWCONFIGVIEW: 'iwms.facility.innerConfig.binViewConfigView',
  RFHOTKEYCONFIG:'iwms.facility.innerConfig.rfHotKeyConfig',
  BINVIEWCONFIGEDIT: 'iwms.facility.innerConfig.binViewConfigEdit',
  HOTKEYCONFIGVIEW: 'iwms.facility.innerConfig.hotKeyConfigView',
  HOTKEYCONFIGEDIT: 'iwms.facility.innerConfig.hotKeyConfigEdit',
  RFOPERATECONFIGVIEW: 'iwms.facility.innerConfig.rfOperateConfigView',
  RFOPERATECONFIGEDIT: 'iwms.facility.innerConfig.rfOperateConfigEdit',

  RECEIVEPRINTCONTAINERCONFIGVIEW: 'iwms.facility.innerConfig.receivePrintContainerConfigView',
  RECEIVEPRINTCONTAINERCONFIGEDIT: 'iwms.facility.innerConfig.receivePrintContainerConfigEdit',
  PICKPRINTCONTAINERCONFIGVIEW: 'iwms.facility.innerConfig.pickPrintContainerConfigView',
  PICKPRINTCONTAINERCONFIGEDIT: 'iwms.facility.innerConfig.pickPrintContainerConfigEdit',

  RECEIVECONFIGVIEW:'iwms.facility.innerConfig.receiveConfigView',
  RECEIVECONFIGEDIT:'iwms.facility.innerConfig.receiveConfigEdit',
  VALIDSTOCKCONFIGVIEW:'iwms.facility.innerConfig.validStockConfigView',
  VALIDSTOCKCONFIGEDIT:'iwms.facility.innerConfig.validStockConfigEdit',
  STOCKOUTCONFIGVIEW:'iwms.facility.innerConfig.stockOutConfigView',
  STOCKOUTCONFIGEDIT:'iwms.facility.innerConfig.stockOutConfigEdit',
  MOVERULECONFIGVIEW:'iwms.facility.innerConfig.moveRuleConfigView',
  DECINCCONFIGVIEW:'iwms.facility.innerConfig.decIncConfigView',
  LOCKCONFIGVIEW:'iwms.facility.innerConfig.lockConfigView',
  CLOSECONFIGVIEW:'iwms.facility.innerConfig.closeConfigView',
  CONTAINERTYPEBINDCONFIGVIEW:'iwms.facility.innerConfig.containerTypeBindConfigView',
  CONTAINERTYPEBINDCONFIGEDIT:'iwms.facility.innerConfig.containerTypeBindConfigEdit',
  CONTAINERBINDMERGECONFIGVIEW:'iwms.facility.innerConfig.containerBindMergeConfigView',
  CONTAINEROPPORTUNITYCONFIGVIEW:'iwms.facility.freshConfig.containerOpportunityConfigView',
  CONTAINEROPPORTUNITYCONFIGEDIT:'iwms.facility.freshConfig.containerOpportunityConfigEdit',
  BILLQPCSTRCONFIGVIEW:'iwms.facility.innerConfig.billQpcStrConfigView',
  BILLQPCSTRCONFIGEDIT:'iwms.facility.innerConfig.billQpcStrConfigEdit',
  NEGATIVESTOCKCONFIGVIEW:'iwms.facility.innerConfig.negativeStockConfigView',
  NEGATIVESTOCKCONFIGEDIT:'iwms.facility.innerConfig.negativeStockConfigEdit',
  USERCONFIGVIEW: 'iwms.facility.innerConfig.userConfigView',
  USERCONFIGEDIT: 'iwms.facility.innerConfig.userConfigEdit',
  RELATEDBINCONFIGVIEW:'iwms.facility.innerConfig.relatedBinConfigView',
  RELATEDBINCONFIGEDIT:'iwms.facility.innerConfig.relatedBinConfigEdit',
  CONSUMINGINITIATECONFIGVIEW:'iwms.facility.innerConfig.consumingInitiateConfigView',
  CONSUMINGINITIATECONFIGEDIT:'iwms.facility.innerConfig.consumingInitiateConfigEdit',
  //预约配置
  BOOKCONFIG:'iwms.facility.bookConfig',
  BOOKTIMECONFIGVIEW:'iwms.facility.bookConfig.bookTimeConfigView',
  BOOKTIMECONFIGEDIT:'iwms.facility.bookConfig.bookTimeConfigEdit',
  BOOKQPCSTRCONFIGVIEW:'iwms.facility.bookConfig.bookQpcStrConfigView',
  BOOKQPCSTRCONFIGEDIT:'iwms.facility.bookConfig.bookQpcStrConfigEdit',
  //上架配置
  PUTAWAYCONFIG:'iwms.facility.putawayConfig',
  TPUTAWAYCONFIGVIEW:'iwms.facility.putawayConfig.tPutawayConfigView',
  TPUTAWAYCONFIGEDIT:'iwms.facility.putawayConfig.tPutawayConfigEdit',
  BINTYPESTORAGECONFIGVIEW:'iwms.facility.putawayConfig.binTypeStorageConfigView',
  BINTYPESTORAGECONFIGEDIT:'iwms.facility.putawayConfig.binTypeStorageConfigEdit',
  ARTICLESTORAGECONFIGVIEW:'iwms.facility.putawayConfig.articleStorageConfigView',
  ARTICLESTORAGECONFIGEDIT:'iwms.facility.putawayConfig.articleStorageConfigEdit',
  CATEGORYSTORAGECONFIGVIEW:'iwms.facility.putawayConfig.categoryStorageConfigView',
  CATEGORYSTORAGECONFIGEDIT:'iwms.facility.putawayConfig.categoryStorageConfigEdit',
  PICKAREASTORAGECONFIGVIEW:'iwms.facility.putawayConfig.pickareaStorageConfigView',
  PICKAREASTORAGECONFIGEDIT:'iwms.facility.putawayConfig.pickareaStorageConfigEdit',
  PUTAWAYTRANSFERCONFIGVIEW:'iwms.facility.putawayConfig.putawayTransferConfigView',
  PUTAWAYTRANSFERCONFIGEDIT:'iwms.facility.putawayConfig.putawayTransferConfigEdit',
  //作业配置
  TASKCONFIG:'iwms.facility.taskConfig',
  TASKSCOPECONFIGVIEW:'iwms.facility.taskConfig.taskScopeConfigView',
  TASKSCOPECONFIGEDIT:'iwms.facility.taskConfig.taskScopeConfigEdit',
  PICKSCOPECONFIGVIEW:'iwms.facility.taskConfig.pickScopeConfigView',
  PICKSCOPECONFIGEDIT:'iwms.facility.taskConfig.pickScopeConfigEdit',
  //退货配置
  RTNCONFIG:'iwms.facility.rtnConfig',
  VENDORRTNBINCONFIGVIEW:'iwms.facility.rtnConfig.vendorRtnBinConfigView',
  VENDORRTNBINCONFIGEDIT:'iwms.facility.rtnConfig.vendorRtnBinConfigEdit',
  VENDORCOLLECTBINCONFIGVIEW:'iwms.facility.rtnConfig.vendorCollectBinConfigView',
  VENDORCOLLECTBINCONFIGEDIT:'iwms.facility.rtnConfig.vendorCollectBinConfigEdit',
  VENDORPICKERCONFIGVIEW:'iwms.facility.rtnConfig.vendorPickerConfigView',
  VENDORPICKERCONFIGEDIT:'iwms.facility.rtnConfig.vendorPickerConfigEdit',
  ALLOWVENDORRTNCONFIGVIEW:'iwms.facility.rtnConfig.allowVendorRtnConfigView',
  ALLOWVENDORRTNCONFIGEDIT:'iwms.facility.rtnConfig.allowVendorRtnConfigEdit',
  //出库配置
  OUTCONFIG:'iwms.facility.outConfig',
  BEYONDCONTROLDAYCONFIGVIEW:'iwms.facility.outConfig.beyondControlDayConfigView',
  BEYONDCONTROLDAYCONFIGEDIT:'iwms.facility.outConfig.beyondControlDayConfigEdit',
  UNIFYWAVEEXEMULTIPLECONFIGVIEW:'iwms.facility.outConfig.unifyWaveExeMultipleConfigView',
  UNIFYWAVEEXEMULTIPLECONFIGEDIT:'iwms.facility.outConfig.unifyWaveExeMultipleConfigEdit',
  COLLECTIONBINREVIEWSHIPCONFIGVIEW:'iwms.facility.outConfig.collectionBinReviewShipConfigView',
  COLLECTIONBINREVIEWSHIPCONFIGEDIT:'iwms.facility.outConfig.collectionBinReviewShipConfigEdit',
  ATTACHMENTCONFIGVIEW:'iwms.facility.outConfig.attachmentConfigView',
  ATTACHMENTCONFIGEDIT:'iwms.facility.outConfig.attachmentConfigEdit',

  ABNORMALPRODUCTOUTCONFIGVIEW:'iwms.facility.outConfig.abnormalProductOutConfigView',
  ABNORMALPRODUCTOUTCONFIGEDIT:'iwms.facility.outConfig.abnormalProductOutConfigEdit',

  PICKRELEASECONFIGVIEW:'iwms.facility.outConfig.pickReleaseConfigView',
  PICKRELEASECONFIGEDIT:'iwms.facility.outConfig.pickReleaseConfigEdit',

  WHOLECONTAINERTYPECONFIGVIEW:'iwms.facility.outConfig.wholeContainerTypeConfigView',
  WHOLECONTAINERTYPECONFIGEDIT:'iwms.facility.outConfig.wholeContainerTypeConfigEdit',
  COLLECTSCHEMECONFIGVIEW:'iwms.facility.outConfig.collectSchemeConfigView',
  COLLECTSCHEMECONFIGEDIT:'iwms.facility.outConfig.collectSchemeConfigEdit',
  STOREALLOCATEBINCONFIGVIEW:'iwms.facility.outConfig.storeAllocateBinConfigView',
  STOREALLOCATEBINCONFIGEDIT:'iwms.facility.outConfig.storeAllocateBinConfigEdit',
  STOREPICKORDERCONFIGVIEW:'iwms.facility.outConfig.storePickOrderConfigView',
  STOREPICKORDERCONFIGEDIT:'iwms.facility.outConfig.storePickOrderConfigEdit',
  DOCKGROUPCONFIGVIEW:'iwms.facility.outConfig.dockGroupConfigView',
  DOCKGROUPCONFIGEDIT:'iwms.facility.outConfig.dockGroupConfigEdit',
  PRINTERCONFIGVIEW:'iwms.facility.outConfig.printerConfigView',
  PRINTERCONFIGEDIT:'iwms.facility.outConfig.printerConfigEdit',
  BINSCOPEPRINTERCONFIGVIEW:'iwms.facility.outConfig.binScopePrinterConfigView',
  BINSCOPEPRINTERCONFIGEDIT:'iwms.facility.outConfig.binScopePrinterConfigEdit',

  EANPRINTERCONFIGVIEW:'iwms.facility.outConfig.eanPrinterConfigView',
  EANPRINTERCONFIGEDIT:'iwms.facility.outConfig.eanPrinterConfigEdit',

  PRINTLABELCONFIGVIEW:'iwms.facility.outConfig.printLabelConfigView',
  PRINTLABELCONFIGEDIT:'iwms.facility.outConfig.printLabelConfigEdit',
  PICKBINORDERCONFIGEDIT:'iwms.facility.outConfig.pickBinOrderConfigEdit',
  PICKBINORDERCONFIGVIEW:'iwms.facility.outConfig.pickBinOrderConfigView',
  // BARCODESPC_REVIEW_CONFIG_EDIT: 'iwms.facility.outConfig.barcodeSpcConfigView',
  // BARCODESPC_REVIEW_CONFIG_VIEW: 'iwms.facility.outConfig.barcodeSpcConfigEdit',
  CONTAINER_FULL_REVIEW_CONFIG_EDIT: 'iwms.facility.outConfig.containerFullReviewConfigEdit',
  CONTAINER_FULL_REVIEW_CONFIG_VIEW: 'iwms.facility.outConfig.containerFullReviewConfigView',
  ALC_OBJECT_TYPE_FORBID_CONTAINER_TYPE_EDIT: 'iwms.facility.outConfig.alcObjectTypeForbidContainerTypeConfigEdit',
  ALC_OBJECT_TYPE_FORBID_CONTAINER_TYPE_VIEW: 'iwms.facility.outConfig.alcObjectTypeForbidContainerTypeConfigView',
  ALC_DIFF_ALLOW_NON_ALC_CONFIG_EDIT: 'iwms.facility.outConfig.alcDiffAllowNonAlcConfigEdit',
  ALC_DIFF_ALLOW_NON_ALC_CONFIG_VIEW: 'iwms.facility.outConfig.alcDiffAllowNonAlcConfigView',
  LABELSUMMARYCONFIGVIEW:'iwms.facility.outConfig.labelSummaryConfigView',
  LABELSUMMARYCONFIGEDIT:'iwms.facility.outConfig.labelSummaryConfigEdit',
  WHOLETRAYPRIORITYCONFIGVIEW:'iwms.facility.outConfig.wholeTrayPriorityConfigView',
  WHOLETRAYPRIORITYCONFIGEDIT:'iwms.facility.outConfig.wholeTrayPriorityConfigEdit',

  STORECONTAINERTYPECONFIGVIEW:'iwms.facility.outConfig.storeContainerTypeConfigView',
  STORECONTAINERTYPECONFIGEDIT:'iwms.facility.outConfig.storeContainerTypeConfigEdit',

  STOCKALLOCATETYPECONFIGVIEW:'iwms.facility.outConfig.stockAllocateTypeConfigView',
  STOCKALLOCATETYPECONFIGEDIT:'iwms.facility.outConfig.stockAllocateTypeConfigEdit',
  //日结配置
  DAILYKNOTSCONFIG:'iwms.facility.dailyKnotsConfig',
  BILLDAILYKNOTSCONFIGVIEW:'iwms.facility.dailyKnotsConfig.billDailyKnotsConfigView',
  BILLDAILYKNOTSCONFIGEDIT:'iwms.facility.dailyKnotsConfig.billDailyKnotsConfigEdit',
  //接口配置
  INTERFACECONFIG:'iwms.facility.interfaceConfig',
  BILLINTERFACECONFIGVIEW:'iwms.facility.interfaceConfig.billInterfaceConfigView',
  BILLINTERFACECONFIGEDIT:'iwms.facility.interfaceConfig.billInterfaceConfigEdit',
  //生鲜配置
  FRESHCONFIG:'iwms.facility.freshConfig',
  RECEIVENOTECONFIGVIEW:'iwms.facility.freshConfig.receiveNoteConfigView',
  RECEIVENOTECONFIGEDIT:'iwms.facility.freshConfig.receiveNoteConfigEdit',
  STOREGROUPCONFIGVIEW:'iwms.facility.freshConfig.storeGroupConfigView',
  STOREGROUPCONFIGEDIT:'iwms.facility.freshConfig.storeGroupConfigEdit',
  ARTICLEGROUPCONFIGVIEW:'iwms.facility.freshConfig.articleGroupConfigView',
  ARTICLEGROUPCONFIGEDIT:'iwms.facility.freshConfig.articleGroupConfigEdit',
  FRESHTASKCONFIGVIEW:'iwms.facility.freshConfig.freshTaskConfigView',
  FRESHTASKCONFIGEDIT:'iwms.facility.freshConfig.freshTaskConfigEdit',
  ARTICLETASKCONFIGVIEW:'iwms.facility.freshConfig.articleTaskConfigView',
  ARTICLETASKCONFIGEDIT:'iwms.facility.freshConfig.articleTaskConfigEdit',
  FRESHPICKORDERCONFIGVIEW:'iwms.facility.freshConfig.freshPickOrderConfigView',
  FRESHPICKORDERCONFIGEDIT:'iwms.facility.freshConfig.freshPickOrderConfigEdit',
  FRESHPICKTEMPBINCONFIGVIEW:'iwms.facility.freshConfig。freshPickTempBinConfigView',
  FRESHPICKTEMPBINCONFIGEDIT:'iwms.facility.freshConfig。freshPickTempBinConfigEdit',
  STOREALLOCATIONSCHEMECONFIGVIEW:'iwms.facility.freshConfig.freshStoreAllocateConfigView',
  STOREALLOCATIONSCHEMECONFIGGEDIT:'iwms.facility.freshConfig.freshStoreAllocateConfigEdit',
  OUTSTOREALLOCATIONSCHEMECONFIGVIEW:'iwms.facility.outConfig.storeAllocateConfigView',
  OUTSTOREALLOCATIONSCHEMECONFIGEDIT:'iwms.facility.outConfig.storeAllocateConfigEdit',
  FRESHPICKAREACONFIGVIEW:'iwms.facility.freshConfig.freshPickareaConfigView',
  FRESHPICKAREACONFIGEDIT:'iwms.facility.freshConfig.freshPickareaConfigEdit',
  ARTICLEALLOCATIONCONFIGVIEW:'iwms.facility.freshConfig.articleAllocationConfigView',
  ARTICLEALLOCATIONCONFIGEDIT:'iwms.facility.freshConfig.articleAllocationConfigEdit',
  FRESHPICKPRINTCONFIGVIEW:'iwms.facility.freshConfig.freshPickPrintConfigView',
  FRESHPICKPRINTCONFIGEDIT:'iwms.facility.freshConfig.freshPickPrintConfigEdit',
  FRESHSTOCKOUTCONFIGVIEW:'iwms.facility.freshConfig.freshStockOutConfigView',
  FRESHSTOCKOUTCONFIGEDIT:'iwms.facility.freshConfig.freshStockOutConfigEdit',
  RFPICKTASKCONFIGVIEW:'iwms.facility.freshConfig.rfPickTaskConfigView',
  RFPICKTASKCONFIGEDIT:'iwms.facility.freshConfig.rfPickTaskConfigEdit',
  //TMS配置
  TMSCONFIG:'iwms.facility.tmsConfig',
  SHIPPLANDISPATCHCONFIGVIEW:'iwms.facility.tmsConfig.shipplandispatchconfigView',
  SHIPPLANDISPATCHCONFIGEDIT:'iwms.facility.tmsConfig.shipplandispatchconfigEdit',
  RETURNDISTRIBUTIONTYPECONFIGVIEW:'iwms.facility.tmsConfig.returnDistributionTypeConfigView',
  RETURNDISTRIBUTIONTYPECONFIGEDIT:'iwms.facility.tmsConfig.returnDistributionTypeConfigEdit',
  SHIP_QTYSTR_SOURCE_CONFIG_VIEW: 'iwms.facility.tmsConfig.shipQtyStrSourceConfigView',
  SHIP_QTYSTR_SOURCE_CONFIG_EDIT: 'iwms.facility.tmsConfig.shipQtyStrSourceConfigEdit',
};
