export const onlFormField = [
	{
		dbFieldName : "PRETYPE",
		dbFieldTxt : "配单类型",
		dbIsKey : false,
		dbIsNull : true,
		dbType : "string",
		dbLength : 10,
		dbPointLength : "",
		dbDefaultVal : "",
		fieldShowType : "select",
		dictField : "",
		dictTable : "",
		dictText : "",
		dictValue : "",     // 新增字段
        placeholder: "请选择配单类型",    // 新增字段
		fieldHref : "",
		fieldLength : "",
		fieldValidType : "",
		fieldMustInput : true,
		fieldExtendJson : "",
		fieldDefaultValue : "",
		isReadOnly : false,
		mainTable : "",
		mainField : "",
		orderNum : 1,
		converter : "",
	},
	{
		dbFieldName : "SCHEDULINGTYPE",
		dbFieldTxt : "调度类型",
		dbIsKey : false,
		dbIsNull : false,
		dbType : "string",
		dbLength : 10,
		dbPointLength : "",
		dbDefaultVal : "UNIFY",
		fieldShowType : "select",
		dictField : "",
		dictTable : "",
		dictText : "",
		dictValue : '{"UNIFY":"统配","ONESTEPCROSS":"一步越库"}',     // 新增字段
        placeholder: "请选择调度类型",    // 新增字段
		fieldHref : "",
		fieldLength : "",
		fieldValidType : "",
		fieldMustInput : true,
		fieldExtendJson : "",
		fieldDefaultValue : "",
		isReadOnly : false,
		mainTable : "",
		mainField : "",
		orderNum : 2,
		converter : "",
	},
	{
		dbFieldName : "EXPIREDATE",
		dbFieldTxt : "到效日期",
		dbIsKey : false,
		dbIsNull : false,
		dbType : "string",
		dbLength : 10,
		dbPointLength : "",
		dbDefaultVal : "",
		fieldShowType : "date",
		dictField : "",
		dictTable : "",
		dictText : "",
		dictValue : "",     // 新增字段
        placeholder: "请选择到效日期",    // 新增字段
		fieldHref : "",
		fieldLength : "",
		fieldValidType : "",
		fieldMustInput : true,
		fieldExtendJson : "",
		fieldDefaultValue : "",
		isReadOnly : false,
		mainTable : "",
		mainField : "",
		orderNum : 3,
		converter : "",
	},
	{
		dbFieldName : "SOURCEBILLNUMBER",
		dbFieldTxt : "来源单号",
		dbIsKey : false,
		dbIsNull : true,
		dbType : "string",
		dbLength : 10,
		dbPointLength : "",
		dbDefaultVal : "",
		fieldShowType : "input",
		dictField : "",
		dictTable : "",
		dictText : "",
		dictValue : "",     // 新增字段
        placeholder: "请输入来源单号",    // 新增字段
		fieldHref : "",
		fieldLength : "",
		fieldValidType : "",
		fieldMustInput : true,
		fieldExtendJson : "",
		fieldDefaultValue : "",
		isReadOnly : false,
		mainTable : "",
		mainField : "",
		orderNum : 4,
		converter : "",
	},
	{
		dbFieldName : "WEIGHT",
		dbFieldTxt : "重量",
		dbIsKey : false,
		dbIsNull : true,
		dbType : "number",
		dbLength : 10,
		dbPointLength : "",
		dbDefaultVal : "",
		fieldShowType : "number",
		dictField : "",
		dictTable : "",
		dictText : "",
		dictValue : "",     // 新增字段
        placeholder: "请输入重量",    // 新增字段
		fieldHref : "",
		fieldLength : "",
		fieldValidType : "",
		fieldMustInput : true,
		fieldExtendJson : "",
		fieldDefaultValue : "",
		isReadOnly : false,
		mainTable : "",
		mainField : "",
		orderNum : 5,
		converter : "",
	},
	{
		dbFieldName : "NOTE",
		dbFieldTxt : "备注",
		dbIsKey : false,
		dbIsNull : true,
		dbType : "string",
		dbLength : 10,
		dbPointLength : "",
		dbDefaultVal : "",
		fieldShowType : "textarea",
		dictField : "",
		dictTable : "",
		dictText : "",
		dictValue : "",     // 新增字段
        placeholder: "请输入备注",    // 新增字段
		fieldHref : "",
		fieldLength : "",
		fieldValidType : "",
		fieldMustInput : true,
		fieldExtendJson : "",
		fieldDefaultValue : "",
		isReadOnly : false,
		mainTable : "",
		mainField : "",
		orderNum : 6,
		converter : "",
	},
]