import { formatMessage } from 'umi/locale';
export const vehicleDispatchingLocale = {
  orderBillTransportTitle: formatMessage({id:'vehicleDispatching.orderBillTransportTitle'}),
  pendingOrderBillTitle: formatMessage({id:'vehicleDispatching.pendingOrderBillTitle'}),
  createShipPlanBillTitle: formatMessage({id:'vehicleDispatching.createShipPlanBillTitle'}),
  shipPlanBillListTitle: formatMessage({id:'vehicleDispatching.shipPlanBillListTitle'}),
  shipPlanBill: formatMessage({id:'vehicleDispatching.shipPlanBill'}),
  sourceNum: formatMessage({id:'vehicleDispatching.sourceNum'}),
  waveNum: formatMessage({id:'vehicleDispatching.waveNum'}),
  orderNum: formatMessage({id:'vehicleDispatching.orderNum'}),
  shipPlanBillNum: formatMessage({id:'vehicleDispatching.shipPlanBillNum'}),
  wmsNumber:formatMessage({id:'vehicleDispatching.wmsNumber'}),
  stat: formatMessage({id:'vehicleDispatching.stat'}),
  shipPlanBillState: formatMessage({id:'vehicleDispatching.shipPlanBillState'}),
  orderType: formatMessage({id:'vehicleDispatching.orderType'}),
  urgencyLevel: formatMessage({id:'vehicleDispatching.urgencyLevel'}),
  pickUpPoint:formatMessage({id:'vehicleDispatching.pickUpPoint'}),
  deliveryPoint: formatMessage({id:'vehicleDispatching.deliveryPoint'}),
  deliveryPointCount: formatMessage({id:'vehicleDispatching.deliveryPointCount'}),
  pickUpPointCount: formatMessage({id:'vehicleDispatching.pickUpPointCount'}),
  cartonCount: formatMessage({id:'vehicleDispatching.cartonCount'}),
  realCartonCount: formatMessage({id:'vehicleDispatching.realCartonCount'}),
  scatteredCount: formatMessage({id:'vehicleDispatching.scatteredCount'}),
  realScatteredCount: formatMessage({id:'vehicleDispatching.realScatteredCount'}),
  totalCartonCount: formatMessage({id:'vehicleDispatching.totalCartonCount'}),
  totalRealCartonCount: formatMessage({id:'vehicleDispatching.totalRealCartonCount'}),
  totalScatteredCount: formatMessage({id:'vehicleDispatching.totalScatteredCount'}),
  totalRealScatteredCount: formatMessage({id:'vehicleDispatching.totalRealScatteredCount'}),
  containerCount: formatMessage({id:'vehicleDispatching.containerCount'}),
  realContainerCount: formatMessage({id:'vehicleDispatching.realContainerCount'}),
  totalContainerCount: formatMessage({id:'vehicleDispatching.totalContainerCount'}),
  totalRealContainerCount: formatMessage({id:'vehicleDispatching.totalRealContainerCount'}),
  orderBillCount: formatMessage({id:'vehicleDispatching.orderBillCount'}),
  volume: formatMessage({id:'vehicleDispatching.volume'}),
  totalVolume: formatMessage({id:'vehicleDispatching.totalVolume'}),
  weight: formatMessage({id:'vehicleDispatching.weight'}),
  totalWeight: formatMessage({id:'vehicleDispatching.totalWeight'}),
  serialArch: formatMessage({id:'vehicleDispatching.serialArch'}),
  vehicle: formatMessage({id:'vehicleDispatching.vehicle'}),
  vehicleNum: formatMessage({id:'vehicleDispatching.vehicleNum'}),
  vehicleType: formatMessage({id:'vehicleDispatching.vehicleType'}),
  carrier: formatMessage({id:'vehicleDispatching.carrier'}),
  order: formatMessage({id:'vehicleDispatching.order'}),
  member: formatMessage({id:'vehicleDispatching.member'}),
  memberType: formatMessage({id:'vehicleDispatching.memberType'}),
  orderDetails:formatMessage({id:'vehicleDispatching.orderDetails'}),
  memberDetails:formatMessage({id:'vehicleDispatching.memberDetails'}),
  modifyButton: formatMessage({id:'vehicleDispatching.modifyButton'}),
  ownerCount: formatMessage({id:'vehicleDispatching.ownerCount'}),
}
