const operationPointLocal = {
  title: '基本资料维护',
  operationPoint: '作业点',
  taskNum: '作业点号',
  taskName: '作业点名称',
  taskOrder: '作业点顺序',
  area: '分区',
  areaNum: '分区编号',
  areaName: '分区名称',
  areaOrder: '分区顺序',
  node: '结点',
  nodeAddress: '结点地址',
  gatewayNum: '网关号',
  nodeType:'结点类型',
  nodeUsage:'结点用途',
  gateway: '网关',
  addGateway: '添加网关',
  section:'区段',
  sectionNum: '区段代码',
  sectionName: '区段名称',
  sectionOrder: '区段顺序',
  bin:'货位',
  binAddress:'货位地址',
  binNum:'货位代码',
  binName:'货位名称',
  binOrder:'货位顺序',
  binSpan: '每次跨度',
  binAdd: '每次新增',

  createBtn:'新建',
  editBtn:'修改',
  batchRemove:'批量移除',
  user:'用户',
  remove:'移除',
  createRole:'新建角色',
  modifyRole:'修改角色',
  progressWarn: '请先勾选',
  progressTitle: '删除',
  authorizeSuccess: '授权成功',
  tabUserInfoTitle: '用户信息',
  tabPermissionInfoTitle: '权限信息',
  noData:'暂无数据',
  added:'已添加',
  number:'个',
  all:'共',
  enabled:'已启用',
  disabled:'已禁用',
  makeSureDelete:'确认移除',
  makeSureDeleteFirst:'确认删除[',
  makeSureDeleteLast:']角色吗?',
  searchPlaceholder:'成员代码/名称',
  deleteRoleFailed: '当前角色下存在用户,不能被删除'
};
export default operationPointLocal
