export const stockTakeBillLocal = {
  title: '盘点单',
  repeatTake: "复盘",
  stockTakePlan: "盘点计划",
  serialNum: "盘点序列号",
  owner: "货主",
  schema: "盘点模式",
  taker: '盘点员',
  snap: "生成快照",
  takeModify: "盘点修改",
  modifyTaker: "修改盘点员",
  modifySchema: "修改盘点模式",
  modifyMethod: "修改盘点方式",
  snapQty: '快照数量',
  snapQtyStr: '快照件数',
  checkQty: '实盘数量',
  checkQtyStr: '实盘件数',
  method: '盘点方式',
  more: '更多',
  repeatCount: "复盘次数",

  beginTakeTime: '开始盘点时间',
  endTakeTime: '结束盘点时间',

  binCount: '总货位数',
  realBinCount: '差异货位数',
  containerCount: '总容器数',
  realContainerCount: '差异容器数',
  articleCount: '总品项数',
  realArticleCount: '差异品项数',
  qtyStr: '总件数',
  decQtyStr: '损耗件数',
  incQtyStr: '溢余件数',
  amount: '总金额',
  realAmount: '差异金额',
  weight: '总重量',
  realWeight: '差异重量',
  volume: '总体积',
  realVolume: '差异体积',
  binLike:'货区/货道/货位'
};